### PR TITLE
Fixes for Ruby 1.8

### PR DESCRIPTION
**Pull request by jarib**
Hi,

I'm quite new to cassandra, at it looks like I unfortunately will need to make this run on 1.8.

I fixed a few syntax errors (trailing commas) + test failures. I have two tests left failing, probably due to unordered Hashes on 1.8:

```
Loaded suite /Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader
Started
................................FF.........................................................................................................................................................................
Finished in 147.524841 seconds.

  1) Failure:
test_get_indexed_slices(CassandraMockTest) [/Users/fijabakk/src/git/cassandra-twitter/test/cassandra_test.rb:842]:
<"row_c_2"> expected but was
<"row_c_4">.

  2) Failure:
test_get_indexed_slices_with_IndexClause_objects(CassandraMockTest) [/Users/fijabakk/src/git/cassandra-twitter/test/cassandra_test.rb:953]:
<"row_c_2"> expected but was
<"row_c_4">.

203 tests, 1042 assertions, 2 failures, 0 errors
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
```

I'm not familiar enough with the Cassandra or the API to fix these though.

### CODE REVIEW

**Comment by natemueller** [comment]
I'll take a look this weekend.  As part of my cleanup in the last release I tried to run tests on 1.8 but ran into a lot of issues building it on modern ubuntu.  I'll give it another go.  I don't think the mock tests will be difficult to clean up.

**Comment by jarib** [comment]
Cool. I'm also working on setting up [a Travis build](https://github.com/jarib/cassandra/blob/travis/.travis.yml) for the gem, that way we can get CI across multiple ruby/cassandra versions.

Currently stuck on a Travis bug (not being able to switch to JDK6 for a Ruby build), but I'll submit a PR when I get it working. After that it's just a question of getting a repo admin to enable the Travis hook.

**Comment by natemueller** [comment]
I'd be happy to turn that on when it's ready.

**Comment by jarib** [comment]
Thanks for merging!

I'm still working on fixes from the Travis people, but got things temporarily running by using "language: java" instead of Ruby. However, it looks like [0.7 is failing](http://travis-ci.org/#!/jarib/cassandra/builds/2124184). Let me know if you'd like this as a bug report.

**Comment by natemueller** [comment]
No, that's fine.  Prior to 1.0 odd releases were development releases.  The APIs aren't stable and this gem doesn't support them.

**Comment by jarib** [comment]
OK, I'll remove that from the Travis build then.

**Comment by natemueller** [comment]
Turns out that was complete nonsense.  I'll take a look at the 0.7 issues.

**Pull request merged**
