### PR TITLE
Initial support for composite column names

### PR DESCRIPTION
**Pull request by psanford**
This patch adds support for composite columns. Here's a brief overview:

Create a new composite column:

```
Cassandra::Composite.new([363].pack('N'), 'extradites-mulling', SimpleUUID::UUID.new().bytes)
```

You can then use this as you would any column name. You can query using the range
predicates:

```
cassandra.get(:CF, key, 
  :start => Cassandra::Composite.new([362].pack('N'),
  :finish => Cassandra::Composite.new([363].pack('N'),
)
```

Cassandra::Composite can also take a :slice => :before or :after to get inclusive or exclusive rage
queries. 

Take a look at the tests for a better idea of how to use it.

### CODE REVIEW

**Comment by rwjblue** [comment]
This looks great!

I'll take a closer look tonight, and get it pulled in.

**Comment by ryanking** [comment]
This looks generally good. Can you add a test that ensures that slicing works properly?

**Comment by psanford** [comment]
Let me make sure I understand what you are looking for.

Do you want me to expand beyond the column slice tests added to cassandra_test.rb? Or are you referring to something else when you say 'slicing'?

**Comment by ryanking** [comment]
Read the comment on http://svn.apache.org/repos/asf/cassandra/trunk/src/java/org/apache/cassandra/db/marshal/CompositeType.java

Note that composite types have specific behavior that makes it possible to do slices with prefixes properly. Make sure that this implementation works with that.

**Comment by Simbul** [comment]
This is very exciting, can't wait to see it in the master branch.

What I'm looking forward to doing by using CompositeType is to replace TimeUUIDType in my application.
Instead of having the column name based on a _timestamp_ + _random seed_ (as is the case with TimeUUID), I'd like to have the column name based on a _timestamp_ + _string ID_ (which I'll provide), and still be able to sort/slice with time predicates as I can do now with TimeUUID columns.

Will that be possible with this patch?

**Comment by mstump** [comment]
Is this pull request dead?

**Comment by psanford** [comment]
I ended up not needing this so I didn't push to get it upstreamed. I believe that the issues that @ryanking mentioned are already addressed in the tests in the patch series.

**Comment by aia** [comment]
Should push it upstream.
I almost ended up reimplementing what you did.

**Comment by aia** [comment]
There's a problem with your implementation, though.

get(CF, key, column) requests where column is CombinedType do not work.

<pre>
Stock cassandra gem:
&gt; db.get(:MyCF, "user11", "\x00\x01\v\x00\x00\x06test11\x00")
 => "test22" 

With your patches:
&gt; db.get(:MyCF, "user11")
 =&gt; #&lt;OrderedHash {#&lt;Composite: ["\v", "test11"]&gt;=&gt;"test22"}
{#&lt;Composite: ["\v", "test11"]&gt;=&gt;1324547723402000}&gt;

But
&gt; column1 = Cassandra::Composite.new("\v", "test11")
 => #&lt;Composite: ["\v", "test11"]&gt;
&gt; db.get(:MyCF, "user11", column1)
 => nil 
</pre>

**Comment by natemueller** [comment]
Updated to fix @aia's issue.  It turns out we needed this after all, so if there's anything more we can do to get it merged in please let me know.

**Comment by aia** [comment]
Looks good!
Thank you for fixing this Nate.

**Comment by relistan** [comment]
Pretty much everyone on the Cassandra project is now recommending Composite Columns over SuperColumns, and CQL uses them by default if you use it to model your data. It would be great if this could get merged in.  Are there outstanding issues that prevent a merge?

**Comment by ryanking** [comment]
I'm willing to merge this, but I don't have time to test (and we don't use this library anymore so we don't spend any time on it)

**Comment by natemueller** [comment]
What kind of testing do you need?  We're using this in production and would be happy to work to get it into the release.

**Comment by relistan** [comment]
Thanks guys for working that out.

**Pull request merged**
